#!/bin/bash
#$ -N parse_haplotypes
#$ -e /u/scratch/r/rwolff/output/
#$ -o /u/scratch/r/rwolff/output/
#$ -cwd
#$ -r y
#$ -j y
#$ -l h_data=20G
#$ -l time=23:00:00
#$ -t 1:41

. /u/local/Modules/default/init/modules.sh
module load anaconda3

conda activate genetic_diversity_utils

readarray good_spec < good_species.txt

good_spec=( null ${good_spec[@]} )

python parse_haplotypes.py --species ${good_spec[$SGE_TASK_ID]}

